### ISSUE TITLE
float:left issue

### ISSUE THREAD

**Issue by yennare** [verekia/initializr-template#17]
when i give float:left; to any element, it stops behave like a relative positioned element, going out of his container div, except for `<p> <a> <span>` elements containing text.
here is some code example:
HTML

``` html
<body>
<div class="hero-unit" id="blabla">
<img src="blabla.jpg"/>
<p>Richard Benson</p>
</div>
</body>
```

CSS

``` css
#blabla img {
float:left;
/* ... */
}
#blabla p {
float:left;
/* ... */
}
```

In this case "float:left" works on `<p>` doesn't works on `<img>`
here some screen:

With float:left; 
http://i.imgur.com/Cj148.jpg

Without float:left;
http://i.imgur.com/FQBJa.jpg

is this an issue or just my ignorance about something?
